#-------------------------------
# General Site Settings

title: Alys Murray - Romance with Heart 
logo: logo.png
email: hello@alysmurray.com
phone: +447419345365
address:

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Books and Movies, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Alys <br> Romance Author

social:
- {icon: "ti-twitter", link: "https://twitter.com/writeralys"}
- {icon: "ti-facebook", link: "https://www.facebook.com/alysmurrayauthor/"}
- {icon: "ti-instagram", link: "https://www.instagram.com/writeralys/"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCEFlLCbgJJJSkyCoKrci_FA"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Alys Murray is an author who writes for the romantic in all of us. Though she graduated with a degree in Drama from NYU’s Tisch School of the Arts and a Master’s in Film Studies from King’s College London, her irrepressible love of romance led her to a career as an author, and she couldn’t be happier to write these stories! 

blurb-btn-link: '/about'
blurb-btn-name: know more



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section

portfolio-home-book-items:


  - image : "assets/images/portfolio/sweet_pea.jpg"
    url: "#"

  - image : "assets/images/portfolio/magnolia_sisters.jpg"
    url: "/books/the-magnolia-sisters"

  - image : "assets/images/portfolio/christmas_company.jpg"
    url: "/books/the-christmas-company"

  - image : "assets/images/portfolio/society_girl.jpg"
    url: "/books/society-girl/"

  - image : "assets/images/portfolio/love_spells.jpg"
    url: "/books/love-spells-for-the-end-of-the-world/"
    
  - image : "assets/images/portfolio/tea_cowboy.jpg"
    url: "/books/tea-and-a-cowboy/"
    


portfolio-home-movie-items:

  - image : "assets/images/portfolio/christmas_louisiana.jpg"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "Novels",
    type : "novels"
  }
- {
    title : "Movies",
    type : "movies"
  }

portfolio-items:
  - image : "assets/images/portfolio/love_spells.jpg"
    url: "#"
    portfolio-type:
     - type: "novels"
    
  - image : "assets/images/portfolio/magnolia_sisters.jpg"
    url: "#"
    portfolio-type:
     - type: "novels"
    
  - image : "assets/images/portfolio/tea_cowboy.jpg"
    url: "#"
    portfolio-type:
     - type: "novels"
    
  - image : "assets/images/portfolio/christmas_company.jpg"
    url: "#"
    portfolio-type:
     - type: "novels"
    
  - image : "assets/images/portfolio/society_girl.jpg"
    url: "#"
    portfolio-type:
     - type: "novels"

  - image : "assets/images/portfolio/christmas_louisiana.jpg"
    url: "#"
    portfolio-type:
     - type: "movies"
     
#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: adam@bath.edu